title: "Parth Desai"
description: "PhD Candidate at The State University of New York at Buffalo"
baseurl: ""
url: "https://parthsam.github.io"
author:
  name: "Parth Desai"
  email: "parthsam@buffalo.edu"
  github: "parthsam"
  linkedin: "www.linkedin.com/in/parth-desai1796"


navbar-links:
  About Me: "aboutme"


page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"


social-network-links:
  email: "parthsam@buffalo.edu"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  
  github: daattali
  linkedin: www.linkedin.com/in/parth-desai1796
 
