title: "Parth Desai"
description: "PhD Candidate at The State University of New York at Buffalo"
baseurl: ""
url: "https://parthsam.github.io"
author:
  name: "Parth Desai"
  email: "parthsam@buffalo.edu"
  github: "parthsam"
  linkedin: "https://www.linkedin.com/in/parthsam"



---
layout: page
title: About
permalink: /about/
---

## Parth Desai

4547 Chestnut Ridge Rd, Apt 209, Buffalo, New York, 14228 | 716-579-6156 | [parthsam@buffalo.edu](mailto:parthsam@buffalo.edu)

### Education
**PhD Candidate, Materials Science**  
The State University of New York at Buffalo, US  
*Expected Summer 2024*

**Master of Science, Materials Science**  
The State University of New York at Buffalo, US  
*Fall 2020*

**Bachelor of Engineering, Chemical Engineering**  
University of Mumbai, India  
*Spring 2019*

### Research Interests
Data-Driven Materials Characterization, Machine Learning in Materials Design, Advanced Analytical Techniques, Feature Extraction and Dimensionality Reduction, Materials Informatics, Algorithm Development, Integration of Experimental and Computational Data, Automation in Materials Science



---
layout: page
title: Projects
permalink: /projects/
---

## Projects

### Microstructure Informatics
**Atomistic Graph-Based Microstructure Representation to Unravel Mechanism of Low Temperature Degradation in Zirconia-Based Ceramics**

- Developed novel feature extraction methods to characterize local atomistic environments and ion distributions, enabling in-depth analysis of phase transformations using atom probe tomography data.
- Introduced a graph-based order parameter to quantify local atomic connectivity, providing valuable insights into the structural arrangement and density of atoms within the local neighborhood.
- Unveiled ion distribution patterns to identify segregation and vacancies within the sample, shedding light on material defects and potential performance limitations.
- Engineered signature functions to distinguish and separate grains and grain boundaries, facilitating accurate material characterization and classification.
- Collaborated effectively with a multidisciplinary team to integrate graph theory principles into materials characterization, demonstrating strong teamwork and problem-solving skills.
- Employed graph algorithms to develop diffusion pathways, enhancing understanding of ion diffusivity and its role in phase transformations.

### Configurable Morphology Distance Operator
- Engineered a data-driven pipeline to uncover and analyze microstructure-property relationships, enhancing material design and development.
- Leveraged graph theory principles and algorithms to construct and evaluate complex morphologies, advancing material research.
- Conducted rigorous experiments and data analysis to validate the distance operator's efficacy, ensuring its reliability for large-scale applications.
- Developed software tools and algorithms to enhance the distance operator's efficiency in processing massive datasets, enabling real-time analysis and decision-making.
- Conceptualized a novel distance operator that extracts structural information and domain-specific features from microstructural data, facilitating clustering of large datasets, leading to improved material characterization and classification.



---
layout: page
title: Publications
permalink: /publications/
---

## Publications

- **P. Desai, N. Juneja, J. Zola, V. Chandola, O. Wodo. COMODO: Configurable Morphology Distance Operator. (Accepted)**
- **P. Desai, B. Mazumder, O. Wodo. Unsupervised learning of local atomistic environments in atom probe tomography data. (in-preparation)**
- **N. Juneja, V. Chandola, J. Zola, O. Wodo and P. Desai. Resource Efficient Bayesian Optimization. (In print)**



---
layout: page
title: Contact
permalink: /contact/
---

## Contact

- **Email**: [parthsam@buffalo.edu](mailto:parthsam@buffalo.edu)
- **Phone**: 716-579-6156
- **GitHub**: [https://github.com/parthsam](https://github.com/parthsam)

[Download my Resume](assets/resume.pdf)

