title: "Parth Desai"
description: "PhD Candidate at The State University of New York at Buffalo"
baseurl: ""
url: "https://parthsam.github.io"
author:
  name: "Parth Desai"
  email: "parthsam@buffalo.edu"
  github: "parthsam"
  linkedin: "https://www.linkedin.com/in/parthsam"
